### PR TITLE
Fix row modification

### LINKED ISSUE #309: Entity.save() includes all fields (instead of only dirty ones)
It seems that each time the complete row data is being saved, even if I change one field.

Meaning, if I change a single field value, for example "weight", the resulting SQL query is like this:
`UPDATE "boxes" SET "id" = $1, "name" = $2, "weight" = $3 WHERE "boxes"."id" = $4 [1, Box A, 12, 1]`
instead of:
`UPDATE "boxes" SET "weight" = $1 WHERE "boxes"."id" = $2 [12, 1]`

Simple example:

```swift
    final class Box : Entity, Preparation {
        
        var name: String
        var weight: Int
        let storage = Storage()
        
        init(name: String, weight: Int) {
            self.name = name
            self.weight = weight
        }
        
        init(row: Row) throws {
            name = try row.get("name")
            weight = try row.get("weight")
        }
        
        func makeRow() throws -> Row {
            var row = Row()
            try row.set("name", name)
            try row.set("weight", weight)
            return row
        }
        
        static func prepare(_ database: Database) throws {
            try database.create(self) {
                builder in
                builder.id()
                builder.string("name")
                builder.int("weight")
            }
        }
        
        static func revert(_ database: Database) throws {
            try database.delete(self)
        }
    }

// Then save and update...

        do {
            let boxA = Box(name: "Box A", weight: 10)
            try boxA.save()

            boxA.weight = 11
            try boxA.save()

            if let boxB = (try Box.all().first) {
                boxB.weight = 12
                try boxB.save()
            }
            
        } catch {
            XCTFail("\(error)")
        }
```

### PR DESCRIPTION
**Pull request by egorzhdan**
Save query will only update dirty fields & id.

This should fix #309

### CODE REVIEW

File: Tests/FluentTests/ModelTests.swift [hunk 1]
```diff
@@ -98,6 +98,63 @@ class ModelTests: XCTestCase {
         XCTAssert(test.id != nil)
     }
 
+    final class Box : Entity, Preparation {
```
Comment (tanner0101) [inline Tests/FluentTests/ModelTests.swift]: `Box` should go in the `Utilities/...` files if possible (to keep unit tests clean).

Comment (egorzhdan) [reply Tests/FluentTests/ModelTests.swift]: Right, I didn't notice the pattern
